from __future__ import annotations

BUILTIN_PROVIDER_TEMPLATES = [
    {
        "id": "custom",
        "name": "Custom",
        "description": "自定义站点，不提供默认签到策略。",
        "login_path": "/login",
        "sign_in_path": "/api/user/checkin",
        "user_info_path": "/api/user/self",
        "api_user_key": "new-api-user",
        "waf_cookie_names": [],
        "supports_cookie_auth": True,
        "supports_browser_login": True,
        "auto_checkin_via_user_info": False,
    },
    {
        "id": "newapi",
        "name": "NewAPI",
        "description": "标准 NewAPI / OneAPI 兼容站点。",
        "login_path": "/login",
        "sign_in_path": "/api/user/checkin",
        "user_info_path": "/api/user/self",
        "api_user_key": "new-api-user",
        "waf_cookie_names": [],
        "supports_cookie_auth": True,
        "supports_browser_login": True,
        "auto_checkin_via_user_info": False,
    },
    {
        "id": "newapi-waf",
        "name": "NewAPI + WAF",
        "description": "带 WAF 的 NewAPI / OneAPI 兼容站点。",
        "login_path": "/login",
        "sign_in_path": "/api/user/checkin",
        "user_info_path": "/api/user/self",
        "api_user_key": "new-api-user",
        "waf_cookie_names": ["acw_tc"],
        "supports_cookie_auth": True,
        "supports_browser_login": True,
        "auto_checkin_via_user_info": False,
    },
    {
        "id": "anyrouter",
        "name": "AnyRouter",
        "description": "AnyRouter 兼容站点模板。",
        "login_path": "/login",
        "sign_in_path": "/api/user/sign_in",
        "user_info_path": "/api/user/self",
        "api_user_key": "new-api-user",
        "waf_cookie_names": ["acw_tc", "cdn_sec_tc", "acw_sc__v2"],
        "supports_cookie_auth": True,
        "supports_browser_login": True,
        "auto_checkin_via_user_info": False,
    },
    {
        "id": "agentrouter",
        "name": "AgentRouter",
        "description": "AgentRouter 兼容站点模板。",
        "login_path": "/login",
        "sign_in_path": "",
        "user_info_path": "/api/user/self",
        "api_user_key": "new-api-user",
        "waf_cookie_names": ["acw_tc"],
        "supports_cookie_auth": True,
        "supports_browser_login": True,
        "auto_checkin_via_user_info": True,
    },
]
